### ISSUE TITLE
Windows 8.1 Support...

### ISSUE THREAD

**Issue by DhruvaBhaskara** [brodysoft/Cordova-SQLitePlugin#166] opened 2014-12-16 08:39 UTC
Hi,

Is Cordova-SQLite plugin is supported for Windows 8.1 metro apps? If yes, when this will get added? If no, is there is any plan for adding support for the same

Regards,
Dhruva

**Comment by brodybits** [comment] 2015-02-06 16:37
Closing as duplicate of #129. Solution already given in pull request #157, which will be integrated once I can test that it is working OK. Please follow #129 for further discussion, you can give a +1 sign.

**Closed by brodybits** 2015-02-06 16:37 UTC
Labels: duplicate, enhancement, question
