### ISSUE TITLE
Where to place de DB File in Android Project

### ISSUE THREAD

**Issue by ro-puente** [brodysoft/Cordova-SQLitePlugin#163] opened 2014-12-04 18:37 UTC
Hey there, this might be a n00b question, but where do I need to place my db file in an android project?

Right now I've tried placing it inside the platforms/android/assets folder, in the same level as the www folder in my ionic project.

**Comment by brodybits** [comment] 2015-01-22 22:09
Duplicate of #10, moving discussion to #172.

**Closed by brodybits** 2015-01-22 22:09 UTC
Labels: duplicate, enhancement, question

**Comment by brodybits** [comment] 2015-02-18 10:51
I have now pushed a new release to master with optional support for pre-populated database. Please see README.md for details.
